name: Build and Release Multi-Platform .NET App

on:
  push:
    tags:
      - 'v**'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [win-x64, linux-x64, osx-x64, linux-arm64, osx-arm64, win-arm64]
    env:
      CONFIGURATION: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish for ${{ matrix.rid }}
        run: |
          dotnet publish -c $CONFIGURATION -r ${{ matrix.rid }} --self-contained true --publish-single-file true -o publish
          cd publish
          zip -r ../release-${{ matrix.rid }}.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.rid }}
          path: release-${{ matrix.rid }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: artifacts/**/release-*.zip
          make_latest: "True"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
